name: sign_l
description: Aplikasi Pembelajaran Bahasa Isyarat Interaktif Berbasis ML.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # --- State Management (Modified MVC) ---
  provider: ^6.1.1 # Untuk ChangeNotifier (Controller) & Dependency Injection

  # # --- Firebase & Backend ---
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # cloud_firestore: ^4.13.6

  # --- Machine Learning & Kamera ---
  camera: ^0.10.5+9 # Akses kamera HP
  tflite_flutter: ^0.10.4 # Engine untuk menjalankan model .tflite (Paling stabil)
  image: ^4.1.3 # Untuk resize, crop, dan normalisasi pixel gambar sebelum masuk ML
  path_provider: ^2.1.1 # Akses direktori penyimpanan sementara HP

  # --- UI/UX & Gamifikasi (Ala Duolingo) ---
  flutter_animate: ^4.5.0 # Animasi UI yang smooth
  lottie: ^2.7.0 # Animasi JSON kompleks (maskot, feedback benar/salah)
  confetti: ^0.7.0 # Efek kembang api saat dapat XP/Level up
  google_fonts: ^6.1.0 # Font yang playful (Nunito, Fredoka, dll)
  cached_network_image: ^3.3.0 # Load gambar materi dari internet dengan cache
  flutter_svg: ^2.0.9 # Render ikon/vektor SVG

  # --- Utilitas ---
  shared_preferences: ^2.2.2 # Cache data lokal sederhana
  intl: ^0.18.1 # Format tanggal dan waktu

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # PENTING: Daftarkan aset ML dan gambar di sini
  assets:
    - assets/ml/model.tflite
    - assets/ml/labels.txt
    - assets/images/
    - assets/animations/
